# Generated by Django 2.2 on 2019-05-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='meddage',
            new_name='message',
        ),
    ]
